version: 2
jobs:
  test-py39:
    docker:
      - image: cimg/python:3.9

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Save Python Version
          command: |
            python --version > pythonversion

      - restore_cache:
          keys:
          - v1-python-{{ checksum "pythonversion" }}-dependencies-{{ checksum "poetry.lock" }}

      - run:
          name: install dependencies
          command: |
            poetry install

            mkdir -p test-reports

      - save_cache:
          paths:
            - ~/.cache/pypoetry/virtualenvs
          key: v1-python-{{ checksum "pythonversion" }}-dependencies-{{ checksum "poetry.lock" }}

      - run:
          name: run tests
          command: |
            poetry run pytest --verbose --junit-xml=test-reports/pytest.xml

      - run:
          name: run lint
          command: |
            poetry run flake8 | tee test-reports/flake8-errors

      - run:
          name: run typechecks
          command: |
            poetry run mypy --junit-xml=test-reports/mypy.xml

      - store_artifacts:
          path: test-reports

      - store_test_results:
          path: test-reports

  publish:
    docker:
      - image: cimg/python:3.9

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Publish to PyPI
          command: |
            export POETRY_HTTP_BASIC_PYPI_USERNAME=$PYPI_USERNAME
            export POETRY_HTTP_BASIC_PYPI_PASSWORD=$PYPI_PASSWORD

            poetry publish --build

workflows:
  version: 2
  test-and-publish:
    jobs:
      - test-py39:
          filters:
            tags:
              only: /.*/
      - publish:
          requires:
            - test-py39
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*.*/
            branches:
              ignore: /.*/
          context: ustack-tornado-shutdown-publisher
